const produtos = [
  {
    id: 1,
    nome: "PlayStation 4 - Bundle 3 Jogos",
    preco: 4500,
    secao: "PlayStation",
    categoria: "Console",
    img: "img/PS4_Bundle.jpg",
    promocao: false,
    precoPromocao: 4000,
    componentes: [
      "Consoles",
      "1 Tb Armazenamento",
      "3 Jogos inclusos",
      "1 Controle de brinde",
    ],
  },
  {
    id: 2,
    nome: "Controle - DualShock 4",
    preco: 259,
    secao: "Acessorios",
    categoria: "Acessorios",
    img: "img/PS4_DualShock4.jpg",
    promocao: false,
    precoPromocao: 230,
    componentes: ["PS4", "Controles", "Carregador incluso"],
  },
  {
    id: 3,
    nome: "Console PlayStation 5 - Digital Edition",
    preco: 3999,
    secao: "PlayStation",
    categoria: "Consoles",
    img: "img/PS5_DigitalEdition.jpg",
    promocao: false,
    precoPromocao: 3599,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 4,
    nome: "Console PlayStation 5",
    preco: 4499,
    secao: "PlayStation",
    categoria: "Consoles",
    img: "img/PS5_FisicalEdition.jpg",
    promocao: false,
    precoPromocao: 4299,
    componentes: ["Nova Geração!", "Dualsense"],
  },
  {
    id: 5,
    nome: "Controle Dualsense - Cosmic Red",
    preco: 499,
    secao: "Acessorios",
    categoria: "Acessorios",
    img: "img/PS5_DualSense.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 6,
    nome: "The Last Of Us - PlayStation 4",
    preco: 179,
    secao: "Jogos",
    categoria: "PlayStation",
    img: "img/TLOU_PS4_Remaster.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 7,
    nome: "The Last of Us Part II - PlayStation 4",
    preco: 179,
    secao: "Jogos",
    categoria: "PlayStation",
    img: "img/TLOU_2_PS4.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 8,
    nome: "God Of War Hits - PlayStation 4",
    preco: 179,
    secao: "Jogos",
    categoria: "PlayStation",
    img: "img/GodOfWar_PS4.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 9,
    nome: "R$50 PlayStation Store",
    preco: 179,
    secao: "Jogos",
    categoria: "PlayStation",
    img: "img/giftCard_PSN.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 10,
    nome: "Console Xbox One S",
    preco: 179,
    secao: "Xbox",
    categoria: "Consoles",
    img: "img/Xbox one S.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 11,
    nome: "Console Xbox Series S",
    preco: 179,
    secao: "Xbox",
    categoria: "Consoles",
    img: "img/Xbox series S.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 12,
    nome: "Console Xbox Series X",
    preco: 179,
    secao: "Xbox",
    categoria: "Acessorios",
    img: "img/Xbox Series X.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 13,
    img: "img/Controle Xbox Series.jpg",
    preco: 179,
    secao: "Acessorios",
    categoria: "Acessorios",
    img: "img/TLOU_2_PS4.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
  {
    id: 14,
    nome: "R$50 Xbox",
    preco: 179,
    secao: "Jogos",
    categoria: "Acessorios",
    img: "img/giftCard_Xbox.jpg",
    promocao: false,
    precoPromocao: 449,
    componentes: [
      "Nova Geração!",
      "Ray-Tracing",
      "SSD ultra rapido",
      "Dualsense",
    ],
  },
];
