const produtos = [
  {
    nome: "Banana",
    preco: 2,
    secao: "hortifruti",
    categoria: "fruta",
    img: "./src/img/banana.png",
  },
  {
    nome: "Morango",
    preco: 2,
    secao: "hortifruti",
    categoria: "fruta",
    img: "./src/img/morango.png",
  },
  {
    nome: "Laranja",
    preco: 2,
    secao: "hortifruti",
    categoria: "fruta",
    img: "./src/img/morango.png",
  },
  {
    nome: "Maçã",
    preco: 2,
    secao: "hortifruti",
    categoria: "fruta",
    img: "./src/img/maca.png",
  },
  {
    nome: "Pão",
    preco: 4,
    secao: "panificadora",
    categoria: "Pães",
    img: "./src/img/pao.png",
  },
  {
    nome: "Pão de Forma",
    preco: 4,
    secao: "panificadora",
    categoria: "Pães",
    img: "./src/img/pao.png",
  },
  {
    nome: "Pão de hot-dog",
    preco: 4,
    secao: "panificadora",
    categoria: "Pães",
    img: "./src/img/pao.png",
  },
  {
    nome: "Leite",
    preco: 5,
    secao: "laticinios",
    categoria: "Leite",
    img: "./src/img/leite.png",
  },
  {
    nome: "Yogurt de Morango",
    preco: 2,
    secao: "laticinios",
    categoria: "Leite",
    img: "./src/img/yogurt_morango.png",
  },
  {
    nome: "Bolo",
    preco: 15,
    secao: "panificadora",
    categoria: "Bolo",
    img: "./src/img/bolo.png",
  },
  {
    nome: "Chocolate",
    preco: 5,
    secao: "laticinios",
    categoria: "Doce",
    img: "./src/img/bolo.png",
  },
  {
    nome: "Queijo",
    preco: 15,
    secao: "laticinios",
    categoria: "Queijo",
    img: "./src/img/bolo.png",
  },
];
